name: Arduino Library Manager Compatibility

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v3
      - uses: arduino/arduino-lint-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          compliance: specification
          project-type: library
          recursive: true
