on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Arduino Lint Check
      - uses: actions/checkout@v3
      - uses: arduino/arduino-lint-action@v1
        with:
          compliance: specification